# Generated by Django 5.1.5 on 2025-02-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='book_author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='book_isbn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='book_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
