# Generated by Django 5.1.5 on 2025-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(choices=[('profile_images/profile_image.svg', 'Profile 1'), ('profile_images/profile_image1.svg', 'Profile 2'), ('profile_images/profile_image2.svg', 'Profile 3'), ('profile_images/profile_image3.svg', 'Profile 4'), ('profile_images/profile_image4.svg', 'Profile 5'), ('profile_images/profile_image5.svg', 'Profile 6')], default='profile_images/profile_image.svg', max_length=255),
        ),
    ]
